server:
  port: @server.port@

mybatis:
  mapper-locations: classpath:/mapper/*mapper.xml

spring:
  datasource:
    driver-class-name: @driver@
    username: @username@
    password: @password@
    url: @jdbcUrl@