# server configuration
server:
  port: @server.port@
# base configuration
spring:
  application:
    name: no-pua-admin
  datasource:
    driver-class-name: @driver@
    username: @username@
    password: @password@
    url: @jdbcUrl@

# mybatis configuration
mybatis:
  mapper-locations: classpath:/mapper/*mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl

# springdoc configuration
springdoc:
  api-docs:
    enabled: true
    path: /v3/api
  swagger-ui:
    path: /v3/api-docs
    tagsSorter: alpha
    use-root-path: true
    enabled: true
    disable-swagger-default-url: true
  packages-to-scan: io.spring.nopua
  paths-to-match: /*
